apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-cadastro-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-cadastro-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: ContainerResource
      containerResource:
        container: api-cadastro-container
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization